PediloOnline/Controllers/ProductosController.cs
using PediloOnline.Data;
using Microsoft.AspNetCore.Mvc;
using PediloOnline.Models;

namespace PediloOnline.Controllers;

public class ProductosController : Controller
{
    private ApplicationDbContext _context;
    public ProductosController(ApplicationDbContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        return View();
    }

}

PediloOnline/Controllers/RubrosController.cs
using Microsoft.AspNetCore.Mvc;
using PediloOnline.Data;
using PediloOnline.Models;
namespace PediloOnline.Controllers;


public class RubrosController : Controller
{
    private ApplicationDbContext _context;

    //CONSTRUCTOR
    public RubrosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View();
    }

    public JsonResult Listado(int? id)
    {
        var tipoRubros = _context.Rubros.ToList();

        if (id !=null)
        {
            tipoRubros = tipoRubros.Where(r => r.RubroID == id).ToList();
        }

        return Json(tipoRubros);
    }

    public JsonResult GuardarRubro(int rubroId, string rubroNombre)
    {
        string resultado = "";

        if (!String.IsNullOrEmpty(rubroNombre))
        {
            rubroNombre = rubroNombre.ToUpper();
            //INGRESA SI ESCRIBIO SI O SI 

            //2- VERIFICAR SI ESTA EDITANDO O CREANDO NUEVO REGISTRO
            if (rubroId == 0)
            {
                //3- VERIFICAMOS SI EXISTE EN BASE DE DATOS UN REGISTRO CON LA MISMA DESCRIPCION
                //PARA REALIZAR ESA VERIFICACION BUSCAMOS EN EL CONTEXTO, ES DECIR EN BASE DE DATOS 
                //SI EXISTE UN REGISTRO CON ESA DESCRIPCION  
                var existeRubro = _context.Rubros.Where(t => t.RubroNombre == rubroNombre).Count();
                if (existeRubro == 0)
                {
                    //4- GUARDAR EL TIPO DE EJERCICIO
                    var tipoRubro = new Rubro
                    {
                        RubroNombre = rubroNombre
                    };
                    _context.Add(tipoRubro);
                    _context.SaveChanges();
                }
                else
                {
                    resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                }
            }
            else
            {
                //QUIERE DECIR QUE VAMOS A EDITAR EL REGISTRO
                var rubroEditar = _context.Rubros.Where(t => t.RubroID == rubroId).SingleOrDefault();
                if (rubroEditar != null)
                {
                    //BUSCAMOS EN LA TABLA SI EXISTE UN REGISTRO CON EL MISMO NOMBRE PERO QUE EL ID SEA DISTINTO AL QUE ESTAMOS EDITANDO
                    var existeTipoEjercicio = _context.Rubros.Where(t => t.RubroNombre == rubroNombre && t.RubroID != rubroId).Count();
                    if (existeTipoEjercicio == 0)
                    {
                        //QUIERE DECIR QUE EL ELEMENTO EXISTE Y ES CORRECTO ENTONCES CONTINUAMOS CON EL EDITAR
                        rubroEditar.RubroNombre = rubroNombre;
                        _context.SaveChanges();
                    }
                    else
                    {
                        resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                    }
                }
            }
        }
        else
        {
            resultado = "DEBE INGRESAR UNA DESCRIPCIÓN.";
        }

        return Json(resultado);
    }

    public JsonResult EliminarRubro(int rubroID) {
        string resultado = "";
        
        var tieneSubrrubro = _context.SubRubros.Any(r => r.RubroID == rubroID); //si encuentra algun rubro que tiene subrubros asociados devuele true  

        if (tieneSubrrubro != true) { 
            var eliminarRubro = _context.Rubros.Find(rubroID);
            _context.Remove(eliminarRubro);
            _context.SaveChanges();
            resultado = "El rubro se elimino correctamente";
        }  else {
            resultado = "No se puede eliminar, el rubro tiene subrubros asociados";
        } 

                 
    

        return Json(resultado);
    }

    public JsonResult TraerRubrosModal(int? rubroId)
    {
        var rubrosPorID = _context.Rubros.ToList();
        if (rubroId != null)
        {
            rubrosPorID = rubrosPorID.Where(e => e.RubroID == rubroId).ToList();
        }

        return Json(rubrosPorID.ToList());
    }


    public JsonResult Buscar(string buscarRubro) {

         if (string.IsNullOrEmpty(buscarRubro))
        {
            return Json(new { results = new List<string>() });
        }

        var rubros = _context.Rubros
            .Where(r => r.RubroNombre.Contains(buscarRubro)) // Busca coincidencias en la columna "Nombre"
            .Select(r => new { r.RubroID, r.RubroNombre })  // Selecciona los campos necesarios
            .ToList();

        return Json(new { rubros });

    }
}

PediloOnline/Controllers/SubrubrosController.cs
using System.IO.Compression;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PediloOnline.Data;
using PediloOnline.Models;
using SQLitePCL;
namespace PediloOnline.Controllers;


public class SubrubrosController : Controller
{
    private ApplicationDbContext _context;

    //CONSTRUCTOR
    public SubrubrosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        var rubros = _context.Rubros.Select(p => new SelectListItem
        {
            Value = p.RubroID.ToString(),
            Text = p.RubroNombre
        }).ToList();

        ViewBag.Rubro = rubros;

        return View(); ;


    }

    public JsonResult ListaSubrubros()
    {
        List<Vistasubrubro> subrubrosMostar = new List<Vistasubrubro>();
        var listadoSubrubros = _context.SubRubros.ToList();

        var listadoRubros = _context.Rubros.ToList();
        foreach (var subrubros in listadoSubrubros)
        {
            var subrubro = listadoSubrubros.Where(t => t.SubRubroID == subrubros.SubRubroID).Single();
            var rubro = listadoRubros.Where(t => t.RubroID == subrubro.RubroID).Single();

            var subrubroMostar = new Vistasubrubro
            {
                SubRubroID = subrubro.SubRubroID,
                RubroID = subrubro.RubroID,
                RubroNombre = rubro.RubroNombre,
                SubRubroNombre = subrubro.SubRubroNombre,


            };
            subrubrosMostar.Add(subrubroMostar);
        }
        return Json(subrubrosMostar);
    }


    public JsonResult GuardarsubRubro(int subRubroID, int RubroID, string subrubroNombre)
    {
        string resultado = "";

        if (!String.IsNullOrEmpty(subrubroNombre))
        {
            subrubroNombre = subrubroNombre.ToUpper();
            //INGRESA SI ESCRIBIO SI O SI 

            //2- VERIFICAR SI ESTA EDITANDO O CREANDO NUEVO REGISTRO
            if (subRubroID == 0)
            {
                //3- VERIFICAMOS SI EXISTE EN BASE DE DATOS UN REGISTRO CON LA MISMA DESCRIPCION
                //PARA REALIZAR ESA VERIFICACION BUSCAMOS EN EL CONTEXTO, ES DECIR EN BASE DE DATOS 
                //SI EXISTE UN REGISTRO CON ESA DESCRIPCION  
                var existesubRubro = _context.SubRubros.Where(t => t.SubRubroNombre == subrubroNombre).Count();
                if (existesubRubro == 0)
                {
                    //4- GUARDAR EL TIPO DE EJERCICIO
                    var tiposubRubro = new SubRubro
                    {
                        RubroID = RubroID,
                        SubRubroID = subRubroID,
                        SubRubroNombre = subrubroNombre
                    };
                    _context.Add(tiposubRubro);
                    _context.SaveChanges();
                }
                else
                {
                    resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                }
            }
            else
            {
                //QUIERE DECIR QUE VAMOS A EDITAR EL REGISTRO
                var subrubroEditar = _context.SubRubros.Where(t => t.SubRubroID == subRubroID).SingleOrDefault();
                if (subrubroEditar != null)
                {
                    //BUSCAMOS EN LA TABLA SI EXISTE UN REGISTRO CON EL MISMO NOMBRE PERO QUE EL ID SEA DISTINTO AL QUE ESTAMOS EDITANDO
                    var existesubRubro = _context.SubRubros.Where(t => t.SubRubroNombre == subrubroNombre && t.SubRubroID != subRubroID).Count();
                    if (existesubRubro == 0)
                    {
                        //QUIERE DECIR QUE EL ELEMENTO EXISTE Y ES CORRECTO ENTONCES CONTINUAMOS CON EL EDITAR
                        subrubroEditar.SubRubroNombre = subrubroNombre;
                        _context.SaveChanges();
                    }
                    else
                    {
                        resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                    }
                }
            }
        }
        else
        {
            resultado = "DEBE INGRESAR UNA DESCRIPCIÓN.";
        }

        return Json(resultado);
    }

    public JsonResult EliminarSubrubro(int subRubroID)
    {
        var subrubro = _context.SubRubros.Find(subRubroID);
        _context.Remove(subrubro);
        _context.SaveChanges();

        return Json(true);
    }
}

PediloOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PediloOnline</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/rubros.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pedilonline.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="~/fontawesome/css/all.min.css" />
</head>

<body>
    <!-- Botón para mostrar/ocultar el menú lateral -->
    <button class="menu-toggle" id="menuToggle">☰</button>
    
    <div class="sidebar" id="sidebarMenu">
        <div class="sidebar-header">
            <h4 class="text-white text-center">PediloOnline</h4>
        </div>
        <a href="@Url.Action("Index", "Home")">Home</a>
        <a href="@Url.Action("Privacy", "Home")">Privacy</a>
        <a href="@Url.Action("Index", "Productos")">Productos</a>
        <a href="@Url.Action("Index", "Carrito")">Carrito</a>
        <a href="@Url.Action("Clientes", "Clientes")">Clientes</a>
        <a href="@Url.Action("Index", "Empresa")">Empresa</a>
        <a href="@Url.Action("Index", "Localidades")">Localidades</a>
        <a href="@Url.Action("Index", "Rubros")">Rubros</a>
        <a href="@Url.Action("Index", "Subrubros")">SubRubros</a>
        <a href="@Url.Action("Marcas", "Marcas")">Marcas</a>
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-color border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="main-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/fontawesome/js/all.min.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>