PediloOnline/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PediloOnline.Models;

namespace PediloOnline.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

PediloOnline/Controllers/LocalidadesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PediloOnline.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using PediloOnline.Data;
using static PediloOnline.Models.Localidad;

namespace PediloOnline.Controllers;

public class LocalidadesController : Controller
{
    private ApplicationDbContext _context;

    public LocalidadesController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
{
    var selectListItems = new List<SelectListItem>
        {
            new SelectListItem { Value = "0", Text = "[SELECCIONE...]"}
        };

        ViewBag.ProvinciaID = selectListItems.OrderBy(t => t.Text).ToList();

    var provincias = _context.Provincias.ToList();
        provincias.Add(new Provincia { ProvinciaID = 0, ProvinciaNombre = "[SELECCIONE...]" });
        ViewBag.ProvinciaID = new SelectList(provincias.OrderBy(c => c.ProvinciaNombre), "ProvinciaID", "ProvinciaNombre");

    return View();
}


     public JsonResult ListadoLocalidades()
     {
         List<Vistalocalidades> LocalidadesMostar = new List<Vistalocalidades>();

         var listadoLocalidades = _context.Localidades.ToList();
         var listadoProvincias = _context.Provincias.ToList();



          foreach (var localidad in listadoLocalidades)
         {
             var provincia = listadoProvincias.Where(t => t.ProvinciaID == localidad.ProvinciaID).Single();
            
             var localidadMostar = new Vistalocalidades
             {
                 LocalidadID = localidad.LocalidadID,
                 ProvinciaID = localidad.ProvinciaID,
                 Nombre = localidad.LocalidadNombre,
                 CodigoPostal = localidad.CodigoPostal, 
                 NombreProvincia = provincia.ProvinciaNombre
              
             };
             LocalidadesMostar.Add(localidadMostar);
         }
         return Json(LocalidadesMostar);
     }

     public JsonResult GuardarLocalidad(
       int LocalidadID,
       string? Nombre,
       string? CodigoPostal,
       int ProvinciaID
       
       )
    {
        string resultado = "";
        Nombre = Nombre.ToUpper();
        if (LocalidadID == 0)
        {
            var localidad = new Localidad
            {
                LocalidadNombre = Nombre,
                CodigoPostal = CodigoPostal,
                ProvinciaID = ProvinciaID
            };
            _context.Add(localidad);
            _context.SaveChanges();

            resultado = "EL REGISTRO SE GUARDO CORRECTAMENTE";
        }
         else
         {
             var editarLocalidad = _context.Localidades.Where(e => e.LocalidadID == LocalidadID).SingleOrDefault();
             if (editarLocalidad != null)
             {
                 editarLocalidad.LocalidadID = LocalidadID;
                 editarLocalidad.LocalidadNombre = Nombre;
                 editarLocalidad.CodigoPostal = CodigoPostal;
                 editarLocalidad.ProvinciaID = ProvinciaID;
                 _context.SaveChanges();

                 resultado = "EL REGISTRO SE ACTUALIZÓ CORRECTAMENTE";
             }
         }
        return Json(resultado);
    }

    public JsonResult TraerLocalidadAlModal(int? LocalidadID)
    {
        var localidadporID = _context.Localidades.ToList();
        if (LocalidadID != null)
        {
            localidadporID = localidadporID.Where(e => e.LocalidadID == LocalidadID).ToList();
        }

        return Json(localidadporID.ToList());
    }


    public JsonResult EliminarLocalidad(int LocalidadID)
   {
    var localidad = _context.Localidades.Find(LocalidadID);
    _context.Remove(localidad);
    _context.SaveChanges();

    return Json(true);
   }
    }

PediloOnline/Controllers/ProductosController.cs
using PediloOnline.Data;
using Microsoft.AspNetCore.Mvc;
using PediloOnline.Models;

namespace PediloOnline.Controllers;

public class ProductosController : Controller
{
    private ApplicationDbContext _context;
    public ProductosController(ApplicationDbContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        return View();
    }

}

PediloOnline/Controllers/RubrosController.cs
using Microsoft.AspNetCore.Mvc;
using PediloOnline.Data;
using PediloOnline.Models;
namespace PediloOnline.Controllers;


public class RubrosController : Controller
{
    private ApplicationDbContext _context;

    //CONSTRUCTOR
    public RubrosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View();
    }

    public JsonResult Listado(int? id)
    {
        var tipoRubros = _context.Rubros.ToList();

        if (id !=null)
        {
            tipoRubros = tipoRubros.Where(r => r.RubroID == id).ToList();
        }

        return Json(tipoRubros);
    }

    public JsonResult GuardarRubro(int rubroId, string rubroNombre)
    {
        string resultado = "";

        if (!String.IsNullOrEmpty(rubroNombre))
        {
            rubroNombre = rubroNombre.ToUpper();
            //INGRESA SI ESCRIBIO SI O SI 

            //2- VERIFICAR SI ESTA EDITANDO O CREANDO NUEVO REGISTRO
            if (rubroId == 0)
            {
                //3- VERIFICAMOS SI EXISTE EN BASE DE DATOS UN REGISTRO CON LA MISMA DESCRIPCION
                //PARA REALIZAR ESA VERIFICACION BUSCAMOS EN EL CONTEXTO, ES DECIR EN BASE DE DATOS 
                //SI EXISTE UN REGISTRO CON ESA DESCRIPCION  
                var existeRubro = _context.Rubros.Where(t => t.RubroNombre == rubroNombre).Count();
                if (existeRubro == 0)
                {
                    //4- GUARDAR EL TIPO DE EJERCICIO
                    var tipoRubro = new Rubro
                    {
                        RubroNombre = rubroNombre
                    };
                    _context.Add(tipoRubro);
                    _context.SaveChanges();
                }
                else
                {
                    resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                }
            }
            else
            {
                //QUIERE DECIR QUE VAMOS A EDITAR EL REGISTRO
                var rubroEditar = _context.Rubros.Where(t => t.RubroID == rubroId).SingleOrDefault();
                if (rubroEditar != null)
                {
                    //BUSCAMOS EN LA TABLA SI EXISTE UN REGISTRO CON EL MISMO NOMBRE PERO QUE EL ID SEA DISTINTO AL QUE ESTAMOS EDITANDO
                    var existeTipoEjercicio = _context.Rubros.Where(t => t.RubroNombre == rubroNombre && t.RubroID != rubroId).Count();
                    if (existeTipoEjercicio == 0)
                    {
                        //QUIERE DECIR QUE EL ELEMENTO EXISTE Y ES CORRECTO ENTONCES CONTINUAMOS CON EL EDITAR
                        rubroEditar.RubroNombre = rubroNombre;
                        _context.SaveChanges();
                    }
                    else
                    {
                        resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                    }
                }
            }
        }
        else
        {
            resultado = "DEBE INGRESAR UNA DESCRIPCIÓN.";
        }

        return Json(resultado);
    }

    public JsonResult EliminarRubro(int rubroID) {
        string resultado = "";
        
        var tieneSubrrubro = _context.SubRubros.Any(r => r.RubroID == rubroID); //si encuentra algun rubro que tiene subrubros asociados devuele true  

        if (tieneSubrrubro != true) { 
            var eliminarRubro = _context.Rubros.Find(rubroID);
            _context.Remove(eliminarRubro);
            _context.SaveChanges();
            resultado = "El rubro se elimino correctamente";
        }  else {
            resultado = "No se puede eliminar, el rubro tiene subrubros asociados";
        } 

                 
    

        return Json(resultado);
    }

    public JsonResult TraerRubrosModal(int? rubroId)
    {
        var rubrosPorID = _context.Rubros.ToList();
        if (rubroId != null)
        {
            rubrosPorID = rubrosPorID.Where(e => e.RubroID == rubroId).ToList();
        }

        return Json(rubrosPorID.ToList());
    }


    public JsonResult Buscar(string buscarRubro) {

         if (string.IsNullOrEmpty(buscarRubro))
        {
            return Json(new { results = new List<string>() });
        }

        var rubros = _context.Rubros
            .Where(r => r.RubroNombre.Contains(buscarRubro)) // Busca coincidencias en la columna "Nombre"
            .Select(r => new { r.RubroID, r.RubroNombre })  // Selecciona los campos necesarios
            .ToList();

        return Json(new { rubros });

    }
}

PediloOnline/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="~/css/Inicio.css" asp-append-version="true" />


<!-- Contenedor Principal -->
<div class="container">
  <h2>INICIO</h2>
  <div class="card main-card">
    <h4>Accesos Rápidos</h4>
    <div class="card-body">
      <div class="row">
        <div class="col-md-4 mb-4 col-sm-12">
          <div class="card custom-card d-flex align-items-center">
            <div class="card-body text-center">
              <a href="@Url.Action("Index", "Localidades")" class="text-decoration-none d-block text-gray">
                <i class="fas fa-city fa-3x mb-3"></i>
                <h5 class="titulo-card mt-2">Localidades</h5>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-4 col-sm-12">
          <div class="card custom-card d-flex align-items-center">
            <div class="card-body text-center">
              <a href="@Url.Action("Clientes", "Clientes")" class="text-decoration-none d-block text-gray">
                <i class="fa fa-users fa-3x mb-3"></i>
                <h5 class="titulo-card mt-2">Clientes</h5>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-4 col-sm-12">
          <div class="card custom-card d-flex align-items-center">
            <div class="card-body text-center">
              <a href="@Url.Action("Index", "Productos")" class="text-decoration-none d-block text-gray">
                <i class="fa fa-cart-plus fa-3x mb-3"></i>
                <h5 class="titulo-card mt-2">Productos</h5>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4 mb-4 col-sm-12">
          <div class="card custom-card d-flex align-items-center">
            <div class="card-body text-center">
              <a href="@Url.Action("Index", "Rubros")" class="text-decoration-none d-block text-gray">
                <i class="fa fa-cog fa-3x mb-3"></i>
                <h5 class="titulo-card mt-2">Rubros</h5>
              </a>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-4 col-sm-12">
          <div class="card custom-card d-flex align-items-center">
            <div class="card-body text-center">
              <a href="@Url.Action("Index", "SubRubros")" class="text-decoration-none d-block text-gray">
                <i class="fa fa-cogs fa-3x mb-3"></i>
                <h5 class="titulo-card mt-2">SubRubros</h5>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>